version: "3.8"

services:
  mariadb:
    image: mariadb:10.8
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed
    environment:
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - mariadb-data:/var/lib/mysql

  redis:
    image: redis:alpine

  frappe:
    image: frappe/bench:latest
    working_dir: /home/frappe
    environment:
      - SHELL=/bin/bash
    volumes:
      - .:/workspace
    ports:
      - "8090:8000"
      - "9090:9000"
    depends_on:
      - mariadb
      - redis
    command: >
      bash -c "
      export PATH=$HOME/.nvm/versions/node/v20.11.1/bin:$PATH &&
      cd /home/frappe &&

      if [ -d 'frappe-bench/apps/frappe' ]; then
        echo 'Bench already exists, skipping init' &&
        cd frappe-bench &&
        bench start;
      else
        echo 'Creating new bench...' &&
        bench init --skip-redis-config-generation frappe-bench &&
        cd frappe-bench &&
        bench set-mariadb-host mariadb &&
        bench set-redis-cache-host redis://redis:6379 &&
        bench set-redis-queue-host redis://redis:6379 &&
        bench set-redis-socketio-host redis://redis:6379 &&
        sed -i '/redis/d' ./Procfile &&
        sed -i '/watch/d' ./Procfile &&
        bench get-app erpnext &&
        bench get-app hrms &&
        bench new-site hrms.localhost --force --mariadb-root-password 123 --admin-password admin --no-mariadb-socket &&
        bench --site hrms.localhost install-app hrms &&
        bench --site hrms.localhost set-config developer_mode 1 &&
        bench --site hrms.localhost enable-scheduler &&
        bench --site hrms.localhost clear-cache &&
        bench use hrms.localhost &&
        bench start;
      fi"

volumes:
  mariadb-data:
